---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk:8
    tag: "8-jdk-alpine"

inputs:
- name: hazardbot-source

run:
  path: hazardbot-source/ci/tasks/build-and-test.sh
