platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk

inputs:
- name: hazardbot-source

outputs:
- name: hazardbot-build-artifacts

run:
  path: hazardbot-source/ci/tasks/build-and-test.sh
