platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jre-alpine

inputs:
- name: hazardbot-source

run:
  path: hazardbot-source/ci/tasks/build-and-test.sh
