platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk

inputs:
- name: hazardbot-source

outputs:
- name: version-file

run:
  path: hazardbot-source/ci/tasks/create-version-file.sh
