---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: hazardbot-source

outputs:
- name: current-app-info

run:
  path: hazardbot-source/ci/tasks/get-current-app-info.sh
