platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk

inputs:
- name: hazardbot-source
- name: hazardbot-source-head

run:
  path: hazardbot-source/ci/tasks/tag-repo.sh
